GET http://localhost:3000/
###
GET http://localhost:3000/products/
###
POST http://localhost:3000/orders
Content-Type: application/json

{
  "ProductID": "MWBLU",
  "Amount": 5
}

###
GET http://localhost:3000/orders/82900ee6-47c6-449b-9126-a8ebac838812
###
POST http://localhost:3000/close

###
GET http://localhost:3000/stats

###
DELETE http://localhost:3000/orders/82900ee6-47c6-449b-9126-a8ebac838812